%%{init:
    {"quadrantChart": {
      "chartWidth": 600,
      "chartHeight": 800,
      "titleFontSize": 23,
      "pointLabelFontSize": 16
    },
    "themeVariables": {
      "quadrant1Fill": "#F28482",
      "quadrant2Fill": "#5E60CE",
      "quadrant3Fill": "#6A994E",
      "quadrant4Fill": "#E0E1DD",
      "quadrant1TextFill": "#343A40",
      "quadrant2TextFill": "#F1F1F1",
      "quadrant3TextFill": "#FFFFFF",
      "quadrant4TextFill": "#343A40",
      "quadrantPointFill": "#000",
      "quadrantPointTextFill": "#293241"
    }
    }}%%
quadrantChart
    title Kano Model for Software Features
    x-axis Low Implementation --> High Implementation
    y-axis Low Satisfaction --> High Satisfaction
    quadrant-1 Excitement Needs
    quadrant-2 Performance Needs
    quadrant-3 Indifferent Needs
    quadrant-4 Basic Needs Meet

    AI-powered recommendations: [0.8, 0.9]
    Virtual reality interface: [0.8, 0.65]
    Real-time collaboration: [0.7, 0.8]
    Fast loading times: [0.6, 0.7]
    Customizable interface: [0.5, 0.6]
    Advanced search: [0.4, 0.53]
    Stable performance: [0.2, 0.1]
    Basic security: [0.1, 0.2]
    Intuitive navigation: [0.3, 0.3]
    Animated loading screens: [0.5, 0.15]
    Holiday-themed icons: [0.6, 0.28]

